FROM ubuntu:22.04

# Instala dependências
RUN apt-get update && apt-get install -y \
    g++ cmake make build-essential \
    libssl-dev wget git \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*

# Copia código
WORKDIR /app
COPY . .

# Copia httplib (header-only)
RUN wget https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h -O /usr/local/include/httplib.h

# Compila
RUN cmake . && make

# Expõe porta
EXPOSE 8080

CMD ["./trabalho04"]
