FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    g++ cmake make build-essential \
    libssl-dev wget git \
    nlohmann-json3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

RUN wget https://raw.githubusercontent.com/yhirose/cpp-httplib/master/httplib.h -O /usr/local/include/httplib.h

RUN cmake . && make

EXPOSE 5001

CMD ["./trabalho04"]
